env: "local"
storage_path: "./storage/storage.db"
http_server:
  address: "localhost:8081"
  timeout: 4s
  shutdown_timeout: 6s
  idle_timeout: 60s
  user: "admin@gmail.com"
  password: "admin"
clients:
  sso:
    address: 'localhost:8082'
    timeout: 10s
    retries_count: 3